### ISSUE TITLE
100.to_string throws System.InvalidOperationException: Sequence contains more than one element

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#150]
# Moved to GitLab

Please continue to the new version of this issue here: https://gitlab.perlang.org/perlang/perlang/-/issues/150. The GitHub page you are currently reading will not contain the latest information on this issue.

---

This one works fine:

```shell
$ perlang -e '100.to_string()'
100
```

However, this one does not:

```shell
$ perlang -e '100.to_string'
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.SingleOrDefault[T](ImmutableArray`1 immutableArray)
   at Perlang.Interpreter.PerlangInterpreter.VisitGetExpr(Get expr) in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 558
   at Perlang.Expr.Get.Accept[TR](IVisitor`1 visitor) in /home/per/git/perlang/Perlang.Common/Expr.cs:line 304
   at Perlang.Interpreter.PerlangInterpreter.Evaluate(Expr expr) in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 703
   at Perlang.Interpreter.PerlangInterpreter.Eval(String source, ScanErrorHandler scanErrorHandler, ParseErrorHandler parseErrorHandler, ResolveErrorHandler resolveErrorHandler, ValidationErrorHandler typeValidationErrorHandler, ValidationErrorHandler immutabilityValidationErrorHandler) in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 386
   at Perlang.ConsoleApp.Program.Run(String source) in /home/per/git/perlang/Perlang.ConsoleApp/Program.cs:line 195
   at Perlang.ConsoleApp.Program.<>c__DisplayClass7_0.<MainWithCustomConsole>b__0(ParseResult parseResult, IConsole console) in /home/per/git/perlang/Perlang.ConsoleApp/Program.cs:line 87
```

This is probably quite reasonable, given that there _are_ indeed multiple `ToString()` overloads for `System.Int32`. Still, this feels highly unreasonable. We could do better.

**Comment by perlun** [comment]
The simplest approach would be to return a list/array of methods in this case. :thinking: If/when we have more complex type analysis in place sometime in the future, we could try and return the "correct" method to return (if there are multiple overloads) based on the left-hand expression type. I.e. assigning to a `Function<String, String>` delegate could return one of the overloads, assigning to a `Function<Integer, String>` could return another and so forth.

Either way, we shouldn't be throwing an exception in this case. More well-defined semantics would be better; even throwing a custom exception would actually be quite fine!

**Comment by perlun** [comment]
Worth mentioning: here's how C# handles it. The following program:

```c#
var foo = "".ToString
```

...generates a compilation error like this:

```
0>/home/per/tmp/ConsoleApp1/ConsoleApp1/Program.cs(3,11): Error CS8917 : The delegate type could not be inferred.
0>------- Finished building project: ConsoleApp1. Succeeded: False. Errors: 1. Warnings: 0
```

This makes sense, and we could do something similar. One obvious problem is that we do not yet have anything similar to "delegates" in the language though... :sweat_smile:

**Comment by perlun** [comment]
Given the non-triviality of fixing this, I think we postpone this to 0.4.0/Later. I'm not sure I want this to block the milestone from being published.
