### ISSUE TITLE
Error on startup: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#155]
Sometimes, I'm seeing errors like this when trying to run a random script:

```
$ perlang docs/examples/hello_world.per 
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'System.Threading.Tasks.TaskCompletionSource`1' from assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Perlang.Interpreter.PerlangInterpreter.<>c.<RegisterGlobalClasses>b__15_0(Assembly a) in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 122
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalClasses() in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 130
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalFunctionsAndClasses() in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 108
   at Perlang.Interpreter.PerlangInterpreter..ctor(Action`1 runtimeErrorHandler, Action`1 standardOutputHandler, IEnumerable`1 arguments, Boolean replMode) in /home/per/git/perlang/Perlang.Interpreter/PerlangInterpreter.cs:line 80
   at Perlang.ConsoleApp.Program..ctor(IEnumerable`1 arguments, Action`1 standardOutputHandler, Action`1 runtimeErrorHandler) in /home/per/git/perlang/Perlang.ConsoleApp/Program.cs:line 142
   at Perlang.ConsoleApp.Program.<>c__DisplayClass7_0.<MainWithCustomConsole>b__0(ParseResult parseResult, IConsole console) in /home/per/git/perlang/Perlang.ConsoleApp/Program.cs:line 99
System.TypeLoadException: Could not load type 'System.Threading.Tasks.TaskCompletionSource`1' from assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

It typically works if I try it again. This feels like a bug in the .NET runtime or something. We'll create this issue for now to see how often it happens, and if there's anything we can do about it.

**Comment by perlun** [comment]
Ran into this now again. Re-ran => it worked right away.

**Comment by perlun** [comment]
> Ran into this now again. Re-ran => it worked right away.

And now. Here's the full stack trace:

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'System.Drawing.Color' from assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XAttribute' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Perlang.Interpreter.PerlangInterpreter.<>c.<RegisterGlobalClasses>b__15_0(Assembly a) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 123
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalClasses() in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 131
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalFunctionsAndClasses() in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 109
   at Perlang.Interpreter.PerlangInterpreter..ctor(Action`1 runtimeErrorHandler, Action`1 standardOutputHandler, IEnumerable`1 arguments, Boolean replMode) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 81
   at Perlang.ConsoleApp.Program..ctor(Boolean replMode, IEnumerable`1 arguments, IEnumerable`1 disabledWarningsAsErrors, Action`1 standardOutputHandler, Action`1 runtimeErrorHandler) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 293
   at Perlang.ConsoleApp.Program.<>c__DisplayClass9_0.<MainWithCustomConsole>b__3(ParseResult parseResult, IConsole console) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 195
System.TypeLoadException: Could not load type 'System.Drawing.Color' from assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XAttribute' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by perlun** [comment]
Interestingly enough, this time it did _not_ work to just re-run it. I'll update to the latest `master` build to see if it helps.

**Comment by perlun** [comment]
Weird. Even upgrading my local .NET SDK (`sudo apt-get install dotnet-sdk-5.0`), bringing in a slew of updates, didn't help. I still cannot run the `0.1.0-dev.161` build.

Interestingly enough though, I can _build_ a local version and run it without problems...

Oh, wait. This **only** happens when I try to run a particular Perlang program I believe (`perlang docs/examples/the-language/defining-and-calling-a-function-with-parameters.per`). How nice. :grin: I think I just found a new bug in Perlang... :wink:

**Comment by perlun** [comment]
(I saw this today on my work machine when running `perlang` without any arguments. Will check and add the version/commit I was using, maybe a stack trace as well if we're lucky.)

**Comment by perlun** [comment]
I'm wondering if this has fixed itself. :thinking: Hasn't seen it recently, even when trying Perlang from time to time (on commit 1b3a5e8). Will close the issue if we don't see this again before 6 February.

**Comment by perlun** [comment]
I saw this error now again on 1b3a5e8 (0.1.0-dev.161), when running [my little `base64_encode` script](https://github.com/perlun/dotfiles/blob/master/bin/base64_encode):

```
$ base64_decode 7QcmfbJkwxKh5ontb2+j0w==
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'System.Drawing.Color' from assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XAttribute' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Perlang.Interpreter.PerlangInterpreter.<>c.<RegisterGlobalClasses>b__15_0(Assembly a) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 123
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalClasses() in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 131
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalFunctionsAndClasses() in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 109
   at Perlang.Interpreter.PerlangInterpreter..ctor(Action`1 runtimeErrorHandler, Action`1 standardOutputHandler, IEnumerable`1 arguments, Boolean replMode) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 81
   at Perlang.ConsoleApp.Program..ctor(Boolean replMode, IEnumerable`1 arguments, IEnumerable`1 disabledWarningsAsErrors, Action`1 standardOutputHandler, Action`1 runtimeErrorHandler) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 293
   at Perlang.ConsoleApp.Program.<>c__DisplayClass9_0.<MainWithCustomConsole>b__3(ParseResult parseResult, IConsole console) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 211
System.TypeLoadException: Could not load type 'System.Drawing.Color' from assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XAttribute' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I'm rather certain that this was caused by #199. Upgrading to 94fe2ca (0.1.0-dev.186) made the `base64_decode` script work again. :tada: I'll close the issue for now.
