### ISSUE TITLE
'System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types' when executing Perlang program from R2R binary

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#199]
### Problem description

Discovered by accident when working on #140 tonight, I think we have a real regression here. Try this for example: `perlang docs/examples/quickstart/hello_world.per`. You'll get an exception like this:

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'System.Drawing.Color' from assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XAttribute' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Perlang.Interpreter.PerlangInterpreter.<>c.<RegisterGlobalClasses>b__15_0(Assembly a) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 123
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalClasses() in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 131
   at Perlang.Interpreter.PerlangInterpreter.RegisterGlobalFunctionsAndClasses() in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 109
   at Perlang.Interpreter.PerlangInterpreter..ctor(Action`1 runtimeErrorHandler, Action`1 standardOutputHandler, IEnumerable`1 arguments, Boolean replMode) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 81
   at Perlang.ConsoleApp.Program..ctor(Boolean replMode, IEnumerable`1 arguments, IEnumerable`1 disabledWarningsAsErrors, Action`1 standardOutputHandler, Action`1 runtimeErrorHandler) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 293
   at Perlang.ConsoleApp.Program.<>c__DisplayClass9_0.<MainWithCustomConsole>b__3(ParseResult parseResult, IConsole console) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 195
System.TypeLoadException: Could not load type 'System.Drawing.Color' from assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XElement' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XAttribute' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
System.TypeLoadException: Could not load type 'System.Xml.Linq.XObject' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

What's _particularly_ nasty is that we test this in CI actually:

https://github.com/perlang-org/perlang/blob/1b3a5e831f8417fae58f2f2c3240f36b354583dc/.github/workflows/website.yml#L23-L24

The reason why the above invocation hasn't been able to spot this particular error is that it can _only_ be reproduced with these self-contained, R2R builds. And the build we produce in `website.yml` is not an R2R build => this bug has managed to slip through.

I _suspect_, as horrible as it seems, that this has been with us all the way since #126 got merged, in February... but I really hope this isn't the case. Anyway, the path forward is two-fold:

### Suggested mitigation steps

1. Make sure this can **never** happen again by ensuring that `website.yml` builds the _same_ kind of build that we actually ship. The whole point of CI is to test stuff as closely as the binaries that will get delivered to our end users, so this is clearly an oversight on my part.

2. Go all the way back to the #126 commit and see if we can reproduce the issue there. If not, `git bisect` is our friend to try and nail this down more thoroughly.

**Comment by perlun** [comment]
The approach described in #200 + `git bisect` helped me find the bad commit - 080b5bfc05f6a8e8e5f9d50e13bcb94b53b8ae98. :tada:
Will try to find the root cause now by studying #191 more carefully.

```
[20:43:02] per@vostro:~/git/perlang ((37c6678...)|BISECTING) $ git bisect good
080b5bfc05f6a8e8e5f9d50e13bcb94b53b8ae98 is the first bad commit
commit 080b5bfc05f6a8e8e5f9d50e13bcb94b53b8ae98
Author: Per Lundberg <perlun@gmail.com>
Date:   Mon May 10 23:36:47 2021 +0300

    (consoleapp) Improve argument parsing (#191)
    
    See https://github.com/perlang-org/perlang/pull/191 for the full details.

 src/Perlang.ConsoleApp/CommandResultExtensions.cs | 34 +++++++++
 src/Perlang.ConsoleApp/Perlang.ConsoleApp.csproj  |  2 +-
 src/Perlang.ConsoleApp/Program.cs                 | 88 ++++++++++++++++-------
 src/Perlang.Tests/ConsoleApp/ProgramTest.cs       |  2 +-
 4 files changed, 100 insertions(+), 26 deletions(-)
 create mode 100644 src/Perlang.ConsoleApp/CommandResultExtensions.cs
```
