### ISSUE TITLE
Operator '>' cannot be applied to operands of type 'System.Numerics.BigInteger' and 'double'

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#229]
The fact that we use `dynamic` for implement our basic arithmetic operators (#227) does have a price: it can cause all forms of nasty bugs. #226 is one such example; the following issue is similar in nature.

All of this stems from the basic fact that _type checking always exists_, regardless of whether a programming environment is "dynamic" or "statically typed". It's just that the type checking is deferred to a _later_ time (runtime) in dynamic environments, where (more of) this can be dealt with at compile-time in statically typed languages.

The `dynamic` keyword in .NET is similar to dynamic programming languages in this regard. It makes you _believe_  your code works, just to make you later realize that it doesn't... at least not for all the permutations of (expected) inputs. :neutral_face: 

```
Perlang Interactive REPL Console (0.1.0-dev.181, built from git commit 9480f21)
> (2 ** 64) > 18446744073709551616.1
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '>' cannot be applied to operands of type 'System.Numerics.BigInteger' and 'double'
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Perlang.Interpreter.PerlangInterpreter.VisitBinaryExpr(Binary expr) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 1008
   at Perlang.Expr.Binary.Accept[TR](IVisitor`1 visitor) in /home/runner/work/perlang/perlang/src/Perlang.Common/Expr.cs:line 101
   at Perlang.Interpreter.PerlangInterpreter.Evaluate(Expr expr) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 827
   at Perlang.Interpreter.PerlangInterpreter.Eval(String source, ScanErrorHandler scanErrorHandler, ParseErrorHandler parseErrorHandler, NameResolutionErrorHandler nameResolutionErrorHandler, ValidationErrorHandler typeValidationErrorHandler, ValidationErrorHandler immutabilityValidationErrorHandler, CompilerWarningHandler compilerWarningHandler) in /home/runner/work/perlang/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 385
   at Perlang.ConsoleApp.Program.Run(String source, CompilerWarningHandler compilerWarningHandler) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 352
   at Perlang.ConsoleApp.Program.RunPrompt() in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 346
   at Perlang.ConsoleApp.Program.<>c__DisplayClass9_0.<MainWithCustomConsole>b__3(ParseResult parseResult, IConsole console) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 180
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by perlun** [comment]
(Oh, and yeah - we should definitely have test coverage to further help us prevent errors like this going forward.)

**Comment by perlun** [comment]
Btw, this is the compile-time error you get if you try to do this in .NET:

```
Cannot apply operator '>' to operands of type 'System.Numerics.BigInteger' and 'double', candidates are: bool >(long, System.Numerics.BigInteger) (in struct BigInteger) bool >(System.Numerics.BigInteger, long) (in struct BigInteger) bool >(System.Numerics.BigInteger, System.Numerics.BigInteger) (in struct BigInteger) bool >(System.Numerics.BigInteger, ulong) (in struct BigInteger) bool >(ulong, System.Numerics.BigInteger) (in struct BigInteger)
```

In other words, this is not a supported comparison. It's fine if we make it unsupported in Perlang also, but we should preferably catch at as early as possible (in `TypeResolver.VisitBinaryExpr()` perhaps?) and handle it gracefully. Not crash like we currently do.

**Comment by perlun** [comment]
Since #227 got merged, this now behaves much more reasonable:

```
Perlang Interactive REPL Console (0.1.0-dev.191, built from git commit b8df032)
> (2 ** 64) > 18446744073709551616.1
[line 1] Operands must be numbers, not bigint and double
>
```

I think that's fine for now; it's a limitation in the language but not a total crash. Closing this issue as "good-enough-for-now".

**Comment by perlun** [comment]
> (Oh, and yeah - we should definitely have test coverage to further help us prevent errors like this going forward.)

Added a test I had in an old stash now in #433.
