### ISSUE TITLE
Investigate Perlang-installer failing on Windows

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#398]
# Moved to GitLab

Please continue to the new version of this issue here: https://gitlab.perlang.org/perlang/perlang/-/issues/398. The GitHub page you are currently reading will not contain the latest information on this issue.

---

As of #389 being merged, we have started seeing a very peculiar error when installing on Windows: https://github.com/perlang-org/perlang/actions/runs/5094377058/jobs/9242418443

I have looked at the code and there's nothing obviously wrong with it: https://github.com/perlang-org/perlang/blob/1f05e2a3219aa539f391641ba046c27d376e177f/src/Perlang.Stdlib/Stdlib/Libc.cs#L61-L66

This is exactly what it should be doing. Still, with the above we get failures like this in CI:

    Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.DllNotFoundException: Unable to load DLL 'libc' or one of its dependencies: The specified module could not be found. (0x8007007E)
       at Perlang.Stdlib.Libc.Internal.write(Int32 fd, IntPtr s, Int32 count) in /home/runner/work/perlang/perlang/src/Perlang.Stdlib/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs:line 27
       at Perlang.ConsoleApp.PerlangConsole.StandardOutStreamWriter.Write(String value) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/PerlangConsole.cs:line 75
       at Perlang.ConsoleApp.Program.<>c__DisplayClass11_0.<MainWithCustomConsole>b__4(ParseResult parseResult, IConsole _) in /home/runner/work/perlang/perlang/src/Perlang.ConsoleApp/Program.cs:line 175
       at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
       at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)

### Thoughts

I'm wondering if this is a new use case we haven't seen previously. :thinking: Until now, we have been _executing_ Windows-only code on Windows, which means that tests dependent on functionality different on Windows (examples: #258 and #269) has been working.

Now, we are talking about something slightly different though: we are cross-compiling for Windows _from Linux_. I'm not sure the `_WINDOWS` define is set in this case, which could very likely be part of the problem here.

**Comment by perlun** [comment]
> Now, we are talking about something slightly different though: we are cross-compiling for Windows _from Linux_. I'm not sure the `_WINDOWS` define is set in this case, which could very likely be part of the problem here.

I think this is precisely the problem. The "fix" in this case would be to compile the Windows binaries in a Windows-based CI job. A bit awkward, but not much to do about it if we want to support Windows (which we want).

**Comment by perlun** [comment]
Regretfully, this will be put on the back burner. We will probably even (temporarily) drop Windows support at some point (until we are a proper, self-hosted LLVM language). Moving to the Later milestone.
