### ISSUE TITLE
argv_pop: Better handling when called when no arguments are available

### ISSUE THREAD

**Issue by perlun** [perlang-org/perlang#84]
The following script:

```perlang
//usr/bin/env perlang $0 "$@" ; exit

print Base64.encode(argv_pop());
```

....is a simple way to base64-encode a string. It works fine, But, if you run it without parameters, the error message produced is quite inadequate:

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Perlang.ConsoleApp.Program.RuntimeError(RuntimeError error)
   at Perlang.Interpreter.PerlangInterpreter.Interpret(IEnumerable`1 statements)
   at Perlang.Interpreter.PerlangInterpreter.Eval(String source, ScanErrorHandler scanErrorHandler, ParseErrorHandler parseErrorHandler, ResolveErrorHandler resolveErrorHandler, TypeValidationErrorHandler typeValidationErrorHandler)
   at Perlang.ConsoleApp.Program.Run(String source)
   at Perlang.ConsoleApp.Program.RunFile(String path)
   at Perlang.ConsoleApp.Program.<>c.<Main>b__4_0(ParseResult parseResult, IConsole console)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

We should try to make this better. From the above, it's not even possible to see where the actual `NullReferenceException` is coming from. That's one that should be fixed. Also, `argv_pop` (which is presumably the method that fails) should handle this scenario more gracefully and not crash like this.

**Comment by perlun** [comment]
A lot has happened since this issue was created; `argv_pop` is no more. It is now called `ARGV.pop` instead. Also, I no longer get the error above with a script like this:

```perlang
#!/usr/bin/env perlang

print(ARGV.pop());
```

When running this, I get the following output:

```
$ perlang foo.per 
[line 3] No arguments left
nil
```

Do note the `nil` there at the end though. It's clearly a bit fishy and it seems like the "No arguments left" exception is somehow considered "non-fatal" and program execution continues... I'll file a separate issue about that. Until the issue has been filed, I will wait with closing this so I don't forget it. (I don't trust my own memory at this age. :older_man:)
